// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env["DATABASE_URL"] ||
  process.env["RENDER_DATABASE_URL"] ||
  process.env["POSTGRES_URL"] ||
  process.env["PGDATABASE_URL"] ||
  "postgresql://postgres:postgres@localhost:5432/lms-db?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
